### ISSUE TITLE
ONP combining puts "|" separated values in the wrong order

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/oncotator#329]
For example two SNPs with a count of ``81`` and ``82`` sequentially, will get rendered as ``82|81``, instead of ``81|82``

**Comment by lbergelson** [comment]
So it's a bit more complicated than just a simple reversal. 

The relevant code is here:  
https://github.com/broadinstitute/oncotator/blob/f4403895c51eaccf9624fb24980111fa8caca083/oncotator/input/OnpQueue.py#L166-L167

```
            values = sorted((set([x.getValue() for x in annotations if x.getValue()])))
            value = "|".join(values)
```

What's happening is that it's reducing the values as a set, and then sorting them according to their natural ordering.  This makes some sense for attributes that are informational strings, but it doesn't make sense for depth values.  

The fix is to replace line 167 with 
```
            values = [x.getValue() for x in annotations if x.getValue()]
```

**Comment by lbergelson** [comment]
On further thought, neither solution is correct.  You end up with things like "Sample1|Sample1|Sample1" which makes everything awful.  @LeeTL1220 How do you feel about reducing to a single value if the annotation values are all identical, but keeping them all pipe separated if they are different at all?

**Comment by LeeTL1220** [comment]
That is how I think it should work.  If all are identical, collapse.  If
one or more differs then use pipes.  I worry about the inconsistency on
number of fields (1 or N) for each entry and the impact of downstream tools.


On Wed, Jul 15, 2015 at 12:56 PM, Louis Bergelson <notifications@github.com>
wrote:

> On further thought, neither solution is correct. You end up with things
> like "Sample1|Sample1|Sample1" which makes everything awful. @LeeTL1220
> <https://github.com/LeeTL1220> How do you feel about reducing to a single
> value if the annotation values are all identical, but keeping them all pipe
> separated if they are different at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/329#issuecomment-121678818>
> .
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632
